spring:
  application:
    name: ownerservice

  # Reactive runtime connection
  r2dbc:
    url: r2dbc:postgresql://localhost:5445/ownerservice
    username: ownerservice
    password: ownerservice

  # JDBC connection only for Liquibase
  datasource:
    url: jdbc:postgresql://localhost:5445/ownerservice
    username: ownerservice
    password: ownerservice
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml 

  mail:
   host: smtp.gmail.com
   port: 587
   username: roomservice.piseth@gmail.com
   password: pmri pwuw zhji xrbk
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true		
server:
  port: 8080

app:
  verification:
    otp-length: 6
    otp-ttl-seconds: 300
    max-attempts: 5
    resend-cooldown-seconds: 60
    otp-pepper: CHANGE-ME-IN-PROD		

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:9090}
  realm: ${KEYCLOAK_REALM:room-system}
  admin:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:owner-service}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:T1cYir3AlWgLcymePdreKx1Urud8bWM6}
  client:
    client-id: ${KEYCLOAK_LOGIN_CLIENT_ID:user-login}
    client-secret: ${KEYCLOAK_LOGIN_CLIENT_SECRET:WTbQbJ3Ld1hoFoZszWyKlwx3Am0HgSL1}